import {
  getLiteralLanguage,
  getLiteralDirection,
  getLiteralType,
  getLiteralValue,
  IStringQuad,
  quadToStringQuad,
  stringQuadToQuad,
  stringToTerm,
  termToString,
  escapeIRI,
  escapeStringRDF,
} from './lib/TermUtil';
export {
  getLiteralLanguage,
  getLiteralDirection,
  getLiteralType,
  getLiteralValue,
  IStringQuad,
  quadToStringQuad,
  stringQuadToQuad,
  stringToTerm,
  termToString,
  escapeIRI,
  escapeStringRDF,
};
